/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PcStockPrice {
        "buttonText": string;
        "checkboxText": string;
        "dollarText": string;
        "eurosText": string;
        "searchPlaceholder": string;
    }
}
declare global {
    interface HTMLPcStockPriceElement extends Components.PcStockPrice, HTMLStencilElement {
    }
    var HTMLPcStockPriceElement: {
        prototype: HTMLPcStockPriceElement;
        new (): HTMLPcStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "pc-stock-price": HTMLPcStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface PcStockPrice {
        "buttonText"?: string;
        "checkboxText"?: string;
        "dollarText"?: string;
        "eurosText"?: string;
        "searchPlaceholder"?: string;
    }
    interface IntrinsicElements {
        "pc-stock-price": PcStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pc-stock-price": LocalJSX.PcStockPrice & JSXBase.HTMLAttributes<HTMLPcStockPriceElement>;
        }
    }
}
